---
# tasks file for couchbase-init
- set_fact:
    host_fqdn: "{{ inventory_hostname + '.' + domain_name }}"
  when: domain_name is defined and inventory_hostname == first_host and '.' not in inventory_hostname
- set_fact:
    rally_point_hostname: "{% if host_fqdn is defined %}{{ host_fqdn }}{% else %}{{ inventory_hostname }}{% endif %}"
  when: inventory_hostname == first_host
- name: Rebalance Cluster
  shell:
    cmd: |
      /opt/couchbase/bin/couchbase-cli rebalance \
        --cluster {{ rally_point_hostname }} \
        --username {{ couchbase_user | default('Administrator') }} \
        --password '{{ couchbase_pass | default('password') }}' \
        --no-progress-bar
  when: inventory_hostname == first_host
